#!/usr/bin/env node
/**
 * PM Agent Pipeline — Demo Runner
 *
 * Creates a complete demo project so you can see what the pipeline produces
 * without having to set up a real project or call any LLMs.
 *
 * Usage: node scripts/demo.js
 * Output: ./__demo__/  (or pass a custom path: node scripts/demo.js ./my-demo)
 *
 * The demo uses "Build a habit tracking app" as the sample idea.
 */

const fs = require("fs");
const path = require("path");

// ─── Config ───────────────────────────────────────────────────────────────────

const DEMO_IDEA = `# Idea: Habit Hive — A Simple Habit Tracking App

**Concept**: A minimal, privacy-first habit tracker that helps people build
and maintain daily routines without gamification overwhelm or social pressure.

**Target user**: Professionals (25–45) who've tried habit tracking before but
abandoned it because existing apps are too noisy, gamified, or require premium
subscriptions for basic features.

**Core hypothesis**: People don't abandon habit tracking because they lack
willpower — they abandon it because the tools get in the way. A deliberately
simple, free, privacy-respecting tracker will retain users 3x longer than the
average habit app.

**Key differentiators**:
- No streaks, no badges, no social features
- One-screen daily check-in (under 10 seconds)
- Weekly/digest view instead of daily pressure
- Local-first (no account required, optional cloud sync)
- Open source`;

const DEMO_CONTENT = {
  "01-discovery": {
    "problems.md": `# Problem Statements — Habit Tracking App

> Generated by: problem-discoverer (v0.1.0)
> Confidence: Strong

## Problem 1: Existing habit apps prioritize engagement over effectiveness

**Statement**: Professionals who want to build habits find that existing apps
(GymStreak, Habitica, Streaks) punish missed days and reward streaks, creating
guilt cycles that cause abandonment rather than consistency.

**Evidence**:
- User review analysis: 68% of negative reviews mention "guilt" or "punishment"
  around missed streaks (source: App Store reviews, top 5 habit apps)
- Survey data: 73% of habit app users quit within 14 days (Journal of Medical
  Internet Research, 2024)
- Internal survey: 12 out of 15 pilot users said "streaks made me feel worse
  when I missed a day"

**Signal strength**: Strong
- Frequency: Mentioned in 4 out of 5 feedback channels
- Severity: Root cause of churn for 68% of users
- Breadth: Affects all habit app users regardless of habit type

**Root cause hypothesis**: The gamification model — streaks, badges, competition —
treats habit formation as a performance, not a practice. This works for games
but backfires for real behavior change.

**What solving this enables**: 3x longer user retention, reduced churn, and a
product that actually helps people rather than extracting engagement.

## Problem 2: Habit tracking adds overhead, not flow

**Statement**: Current habit tracking requires 30–60 seconds per entry — logging,
tagging, rating, reflecting — which is too much friction for daily use and
disrupts the habit itself.

**Evidence**:
- Time-to-log measurements: Average habit app requires 4–7 taps and 30+ seconds
  per entry (usability test, n=20)
- 41% of churned users cite "too much logging" as primary reason (Habitica
  churn survey, 2023)
- Competitive teardown: 8 out of 10 top habit apps require at minimum: open app,
  find habit, tap, rate intensity, add note, confirm

**Signal strength**: Strong
- Frequency: 3rd most common complaint across all sources
- Severity: Direct 1:1 relationship with daily drop-off
- Breadth: Every user faces this friction every single day

**Root cause hypothesis**: Apps are designed for data collection (what did you
do, how did you feel, how intense) rather than for quick acknowledgment (did
you do the thing? yes/no).

## Problem 3: Privacy concerns limit adoption

**Statement**: Users are uncomfortable with habit data being stored on clouds,
analyzed for ad targeting, or sold to insurance/wellness programs, preventing
adoption among privacy-conscious professionals.

**Evidence**:
- 54% of survey respondents said "privacy concerns" was a barrier to trying a
  habit app (Data, privacy & health apps survey, 2024)
- Streaks was acquired by a health insurance data broker in 2022 — trust eroded
- GDPR complaints against 3 major habit apps for unclear data practices

**Signal strength**: Moderate (growing)
- Frequency: Emerging signal, not yet dominant
- Severity: For affected users, it's a hard blocker — they simply won't use
  cloud-dependent apps
- Breadth: ~15% of target demographic, growing ~20% YoY
`,

    "evidence": {
      "sources.md": `# Sources Consulted

1. **App Store Reviews (top 5 habit apps)** — 1,247 reviews analyzed
   - Date: 2025-11 to 2026-02
   - Relevance: Primary source for P1 (streak guilt)

2. **Journal of Medical Internet Research, 2024** — Habit app retention study
   - DOI: 10.2196/42431
   - Relevance: Validates P1 with academic evidence

3. **Internal pilot survey (n=15)** — ProductTribe beta group
   - Date: 2026-01
   - Relevance: Validated all 3 problem statements internally

4. **Competitive teardown** — Habitica, Streaks, GymStreak, Loop, Day One
   - Date: 2026-02
   - Relevance: UX friction analysis for P2

5. **Data, privacy & health apps survey (n=500)** — Harris Poll, 2024
   - Relevance: Privacy barrier data for P3
`,
      "idea-excerpts.md": `# Key Excerpts from Source Material

> "I downloaded three habit apps this year and deleted all three. Not because
> I'm lazy — because they made me feel bad for missing a day."
> — Pilot user #7

> "I spend more time logging my habit than doing it. The irony is incredible."
> — App Store review (Streaks, 2★)

> "I would never let a habit app know when I'm at the gym, or what time I wake
> up. That's my data."
> — Survey respondent, privacy-conscious segment
`,
    },
  },

  "02-validation": {
    "sizing.md": `# Opportunity Sizing — Habit Tracking App

> Generated by: opportunity-validator (v0.1.0)
> Confidence: High

## Market Overview

| Metric | Value | Source |
|--------|-------|--------|
| Global habit tracking app market (2025) | $4.2B | Grand View Research |
| Projected CAGR (2025–2030) | 12.8% | Grand View Research |
| Addressable market (EU + US, professionals 25–45) | 47M users | Statista |
| SAM (privacy-first segment) | 7M users | Adjusted from privacy survey data |
| SOM (Year 1, realistic) | 25,000 users | Bottom-up from pilot channels |

## Competition Landscape

| App | MAU | USP | Gap we exploit |
|-----|-----|-----|----------------|
| Streaks (iOS only) | 500K | Simple, beautiful | Streak guilt, no privacy-first positioning |
| Habitica | 1.2M | Gamified RPG | Overwhelming, not for professionals |
| GymStreak | 300K | Workout-specific | Too narrow, gym-only |
| Loop Habit Tracker | 200K | Open source, free | Ugly UI, no mobile sync |
| Day One | 1.5M | Journaling focus | Not habit-specific, premium priced |

## Revenue Model

| Tier | Price | Features | Est. Conversion |
|------|-------|----------|-----------------|
| Free | $0 | Core habit tracking, local-only | 100% |
| Pro | $3.99/mo | Cloud sync, weekly analytics, export | 8–12% |
| Lifetime | $49.99 | All features forever | 2–3% |

## Financial Projection (Year 1)

| Month | Free Users | Pro Users | Revenue |
|-------|------------|-----------|---------|
| 1 | 2,000 | 160 | $638 |
| 3 | 6,000 | 480 | $1,915 |
| 6 | 15,000 | 1,200 | $4,788 |
| 12 | 25,000 | 2,500 | $9,975 |

## Confidence Assessment

- **Problem validity**: Strong (P1 and P2 validated by multiple sources)
- **Market timing**: Moderate (interest in digital wellness growing, but privacy
  as primary differentiator is unproven at scale)
- **Execution risk**: Low (MVP is a mobile web app, no AI/ML complexity)
- **Competitive risk**: Moderate (Streaks could pivot, Apple Health could add
  habits feature — they have the platform advantage)

## Key Assumptions

1. [PASSED] Users value privacy enough to choose a less feature-rich app (+20M
   privacy downloads exist, Signal proved the model)
2. [PASSED] 10-second daily check-in is sufficient for habit formation (atomic
   habits research supports this)
3. [PASSED] Professionals are willing to pay $3.99/mo (comparable to Calm,
   Headspace, Any.do)
4. [UNKNOWN] "No streaks" positioning is a net positive for retention (needs
   A/B testing — some users ARE motivated by streaks)
5. [PASSED] Local-first architecture is technically feasible (IndexedDB +
   optional sync via WebDAV/CouchDB)
`,
    "assumptions.md": `# Assumptions Log

| # | Assumption | Status | Evidence | Risk |
|---|------------|--------|----------|------|
| 1 | Privacy is a purchase driver for habit apps | PASSED | Signal, ProtonMail proved privacy market; 54% privacy barrier survey | Low |
| 2 | 10-sec check-in is viable for habit formation | PASSED | Atomic Habits (James Clear) — 2-minute rule supports minimal friction | Low |
| 3 | Users pay for habit tools | PASSED | Streaks ($4.99) top-grossing; Habitica subscriptions | Low |
| 4 | "No streaks" is a net positive | UNKNOWN | Needs A/B test; some users want streaks | Medium |
| 5 | Local-first is technically feasible | PASSED | IndexedDB reliable; examples: Obsidian, Standard Notes | Low |
| 6 | 25k users in Y1 is realistic | UNCERTAIN| Depends on distribution (Product Hunt, HN, Reddit) | Medium |
| 7 | No major competitor pivots in 6 months | UNKNOWN | Apple Health adding habits would disrupt | High |
`,
  },

  "03-current-state": {
    "landscape.md": `# Landscape Map — Habit Tracking

> Generated by: current-state-expert (v0.1.0)

## Feature Matrix

| Feature | Habitica | Streaks | GymStreak | Loop | Ours |
|---------|----------|---------|-----------|------|------|
| Daily check-in | ✅ 6+ taps | ✅ 3 taps | ✅ 4 taps | ✅ 3 taps | ✅ 1 tap |
| Streaks/gamification | ✅ Heavy | ✅ Core | ✅ Core | ❌ | ❌ |
| Cloud sync | ✅ | ✅ iCloud | ✅ | ❌ | ✅ Optional |
| Privacy-first | ❌ | ⚠️ | ❌ | ✅ | ✅ Core |
| Open source | ⚠️ Some | ❌ | ❌ | ✅ GPL-3 | ✅ MIT |
| Offline first | ❌ | ✅ | ❌ | ✅ | ✅ |
| Multi-platform | ✅ Web+Mobile | ❌ iOS only | ✅ iOS+Android | ✅ Android only | ✅ PWA |
| Weekly digest | ❌ | ⚠️ Basic | ❌ | ❌ | ✅ Rich |

## Trends

1. **Wellness consolidation**: Apple Health, Google Fit absorbing standalone apps
2. **Privacy backlash**: Post-Roe, post-2A, health data sensitivity is higher than ever
3. **Simplicity renaissance**: Analogue, Minimal, Bear proving "less is more" in apps
4. **Local-first movement**: Obsidian (4M+ users), Linear, Standard Notes validating offline-first UX

## Opportunities

- **Underserved niche**: "Privacy-first, simple" is an empty quadrant in the competitive matrix
- **PWA advantage**: Skip app store review cycles, ship weekly
- **Open source trust**: A MIT-licensed habit tracker with auditable code is a unique trust signal
`,
    "constraints.md": `# Constraints Analysis

## Technical

1. **IndexedDB limits**: 50MB–1GB depending on browser; need clear storage policy
2. **PWA push notifications**: iOS PWA notifications unreliable; need email fallback
3. **No native SDKs**: PWA can't access HealthKit / Google Fit — acceptable for v0

## Business

1. **Revenue ceiling**: $4M ARR at realistic adoption (privacy-first positioning limits
   data monetization, which limits ARPU)
2. **No VC path**: Privacy-first, local-first apps don't fit investor growth patterns
   (Obsidian raised only $350K in seed). Requires bootstrapper mindset.

## Timeline

1. **v0 MVP**: 2 weeks (PWA, single habit, yes/no check-in, weekly digest)
2. **v1 Launch**: 6 weeks (multiple habits, categories, opt-in cloud sync, Pro tier)
3. **v2 Growth**: 12 weeks (analytics, export, API, team/social features)
`,
  },

  "04-solutions": {
    "options.md": `# Solution Options — Habit Tracking App

> Generated by: solution-generator (v0.1.0)

## Option A: Lean MVP — "Habit Hive Lite" ⭐ RECOMMENDED

**One-liner**: A PWA that lets you check off daily habits in one tap. No accounts,
no streaks, no noise.

- **Effort**: 2 weeks (1 developer)
- **Stack**: Next.js PWA + IndexedDB + optional WebDAV sync
- **Core features**: 1-tap check-in, weekly digest (email), max 5 habits
- **Monetization**: Free (build audience first)
- **Why this wins**: Validates the core thesis (simplicity) before building
  anything complex. If people don't stick with the simplest version, complexity
  won't save us.

## Option B: Full App — "Habit Hive Pro"

**One-liner**: A cross-platform habit tracker with cloud sync, analytics, and
pro features from day one.

- **Effort**: 8–10 weeks (2 developers)
- **Stack**: React Native + Firebase + RevenueCat
- **Core features**: All of Option A + iCloud sync, trends analytics, habits
  library (100+ pre-made), pro tier ($3.99/mo)
- **Monetization**: Freemium from day one
- **Risks**: Over-engineered before validation. If the simplicity thesis is
  wrong, we've built the wrong product for 2 months.

## Option C: API-First — "Habit Hive SDK"

**One-liner**: A habit tracking API that other apps embed. We license the engine,
not the interface.

- **Effort**: 12+ weeks (2–3 developers)
- **Stack**: Go API + PostgreSQL + SDKs (JS, Swift, Kotlin)
- **Core features**: Habit CRUD, streak calculation (opt-in), weekly reports,
  data export
- **Monetization**: Per-seat licensing ($0.01/log → ~$3/active user/year)
- **Risks**: B2B sales cycle is long; no direct user feedback loop
`,
    "prototypes": {
      "v1-pipeline-skeleton.py": `# Quick mock of the v1 check-in screen

SCREEN = {
    "name": "Daily Check-in",
    "elements": [
        {"type": "header", "text": "Good morning! ☀️"},
        {"type": "habit_list", "habits": [
            {"name": "Exercise", "done": False, "icon": "🏃"},
            {"name": "Read 20min", "done": True, "icon": "📖"},
            {"name": "Meditate", "done": False, "icon": "🧘"},
            {"name": "Drink water", "done": True, "icon": "💧"},
        ]},
        {"type": "add_habit", "placeholder": "Add a new habit..."},
        {"type": "weekly_progress", "completion_rate": "3/4 today"},
    ]
}

# 1-tap toggle: tap habit → mark done → haptic feedback → done
`,
    },
  },

  "05-assessment": {
    "recommendation.md": `# Recommendation — Habit Tracking App

> Generated by: solution-assessor (v0.1.0)
> Mode: mvp

## Scoring

| Criterion | Weight | Option A | Option B | Option C |
|-----------|--------|----------|----------|----------|
| Time to market | 20% | 5/5 | 2/5 | 1/5 |
| Validation risk | 20% | 5/5 | 3/5 | 4/5 |
| Development cost | 15% | 5/5 | 2/5 | 1/5 |
| Revenue potential | 15% | 3/5 | 4/5 | 3/5 |
| Strategic fit | 15% | 5/5 | 4/5 | 3/5 |
| User delight | 15% | 4/5 | 4/5 | 2/5 |

**Option A: 4.5/5 — ✅ RECOMMENDED**
Option B: 3.1/5 — Acceptable fallback if A validates
Option C: 2.4/5 — Too early

## Why Option A Wins

1. **Tests the core thesis** in 2 weeks: "Will people use a 1-tap habit tracker
   without streaks?" If yes → proceed. If no → pivot before investing 10 weeks.
2. **Builds audience** during validation phase — collect emails, run waitlist,
   get feedback before committing to monetization.
3. **Lowest burn** — one developer, no cloud costs (IndexedDB is free), PWA
   means no app store fees.

## Risk Register

| Risk | Severity | Likelihood | Mitigation |
|------|----------|------------|------------|
| No one downloads it | High | Low | Ship to Product Hunt + HN + r/SideProject |
| Users want streaks | Medium | Medium | A/B test streak toggle in week 3 |
| PWA too limited | Medium | Low | Fallback to React Native in v1 if PWA retention < 20% |
| Apple Health copies feature | Medium | Medium | Compete on privacy — Apple's lock-in is their weakness |
`,
    "risks.md": `# Risk Register

| ID | Risk | Impact | Prob | Mitigation | Owner |
|----|------|--------|------|------------|-------|
| R1 | Users don't see value without streaks | Retention < 20% | M | A/B test streak toggle; add optional streaks | Product |
| R2 | PWA notification limits on iOS | Users miss check-ins | H | Email digest as fallback; target Android + desktop first | Dev |
| R3 | No monetization path (free only) | Can't sustain | L | Introduce Pro plan when MAU > 5K (~month 4) | Business |
| R4 | Apple Health adds habits feature | Market shrinks | M | Double down on cross-platform + open source moat | Strategy |
| R5 | IndexedDB data loss | User frustration | L | Export option + clear storage policy + opt-in sync | Dev |
`,
  },

  "06-design": {
    "design-spec.md": `# Design Specification — Habit Hive

> Generated by: ux-designer (v0.1.0)

## Core Design Principles

1. **One-tap, done**: Every interaction must be completable in one tap or less
2. **No badges, no streaks, no guilt**: No gamification elements that create
   negative feedback loops
3. **Local first**: No account creation, no loading states, no "sign in to continue"
4. **Weekly, not daily pressure**: Weekly digest replaces daily streak mentality

## Screens

### 1. Daily Check-in (Home Screen)
- Shows habits for today with yes/no toggles
- Habits from previous days show completion state (no guilt — just "did/didn't")
- FAB to add new habit
- No streaks, no percentages, no guilt messages

### 2. Weekly Digest
- Delivered Sunday evening (email + in-app)
- Shows: habits completed vs missed, trend (up/down/same), highlight of the week
- Encourages reflection, not comparison

### 3. Settings
- Theme (light/dark/system)
- Habit management (edit, reorder, archive)
- Export data (JSON/CSV)
- Sync configuration (optional)

## User Flow

1. User opens app → sees today's habits → taps habits done → done (5 seconds)
2. End of week → digest arrives → user sees summary → optionally adjusts habits
3. Settings → export data or configure sync (one-time setup)
`,
  },

  "07-design-review": {
    "review.md": `# Design Review — Habit Hive

> Generated by: ux-design-lead (v0.1.0)

## Verdict: APPROVED with minor revisions

### ✅ What works
- 1-tap check-in is the right core loop
- Removing streaks/gamification is bold and defensible
- Weekly digest is a great retention mechanism
- Local-first is technically sound and on-brand

### 🔧 Required revisions
1. **Add a 5-second "how it works" onboarding** — first-time users need to
   understand why there are no streaks. Otherwise they'll think it's broken.
2. **Add haptic feedback on check-in** — the physical sensation of "done" is
   important for habit formation. (PWA haptic is available via vibration API.)
3. **Add a "skip habit" option** — some days a habit isn't relevant; the ability
   to skip without guilt is important (distinct from "didn't do it")

### 💡 Suggestions
- Consider a 2-habit maximum for the first week, then unlock more. Prevents
  overwhelming beginners.
- Weekly digest should be funny/warm, not clinical. Voice matters here.

### ⚠️ Blocking issues
None.
`,
  },

  "08-project-plan": {
    "plan.md": `# Project Plan — Habit Hive v0

> Generated by: project-manager (v0.1.0)

## Timeline (5-week sprint)

| Week | Milestone | Key tasks | Dependencies |
|------|-----------|-----------|--------------|
| 1 | Core check-in | Next.js scaffold, IndexedDB setup, 1-tap habit toggle | None |
| 2 | Weekly digest | Email service (Resend), digest template, weekly aggregation | Week 1 |
| 3 | Release + launch | PWA build, app store skip (PWA), Product Hunt submission | Week 2 |
| 4 | Feedback loop | Add feedback widget, monitor retention, A/B test streak toggle | Week 3 |
| 5 | Iterate | Ship revisions from feedback, add optional cloud sync | Week 4 |

## Team
- 1 full-stack developer (Next.js + PWA)
- 1 designer (part-time, weekly review)
- You (PM + strategy)

## Key Deliverables
- PWA installable on iOS/Android/Desktop
- Core check-in flow with up to 5 habits
- Weekly email digest
- Basic analytics (retention, daily active users, habits completed)
`,
  },

  "09-gtm": {
    "launch-plan.md": `# Go-to-Market Plan — Habit Hive

> Generated by: gtm-designer (v0.1.0)

## Launch Channels

| Channel | Audience | Effort | Expected | Priority |
|---------|----------|--------|----------|----------|
| Product Hunt | $Tech/PM audience | 2 days prep | 500–2K signups | 🔴 Must |
| Hacker News | Builders, privacy-conscious | 1 day prep | 200–1K signups | 🔴 Must |
| r/SideProject | Indie hackers | 30 min post | 100–500 signups | 🟡 High |
| r/privacy | Privacy-focused users | 30 min post | 50–200 signups | 🟡 High |
| Twitter/X | 10 tweets over 2 weeks | 2 hours | 100–300 signups | 🟢 Medium |

## Launch Strategy

1. **Pre-launch (Week 3)**: Build Twitter presence. Tweet daily build progress.
   Collect waitlist emails via landing page.
2. **Launch day (Week 3 Friday)**: Ship to Product Hunt + HN simultaneously.
   Post Show HN with demo GIF.
3. **Post-launch (Week 4)**: Respond to every comment. Ship 3 quick wins from
   feedback. Post "What I learned from launching" on dev.to.

## Messaging

- **Headline**: The habit tracker that doesn't make you feel bad.
- **Tagline**: One tap. No streaks. Done.
- **Key messages**: Privacy-first, open source, designed for real humans not
  gamification dopamine loops.
`,
  },

  "10-feedback": {
    "insights.md": `# Feedback Plan — Habit Hive

> Generated by: feedback-manager (v0.1.0)

## Collection Channels

1. **In-app widget**: Emoji reaction after check-in (😊 😐 😞) — < 1 second
2. **Weekly digest feedback link**: "How was your habit week?" — optional survey
3. **GitHub issues**: Feature requests + bug reports (open source advantage)
4. **User interviews**: 5 users per week starting Week 4

## Metrics to Track

| Metric | Target | Measurement |
|--------|--------|------------|
| DAU (daily check-in completion) | > 60% | In-app analytics |
| 7-day retention | > 40% | Weekly digest opens |
| 30-day retention | > 20% | App opens + digest opens |
| NPS (in-app prompt Week 4) | > 30 | 1-question survey |
| Time to first habit completion | < 10 seconds | In-app analytics |

## Learning Loops

- **Weekly**: Review retention numbers. Identify drop-off points.
- **Monthly**: User interview synthesis. Update problem statements.
- **Quarterly**: Full pipeline re-run with updated Idea.md based on 3 months
  of real data.
`,
  },

  "11-communications": {
    "calendar.md": `# Communications Calendar — Habit Hive Launch

> Generated by: communications-specialist (v0.1.0)

## Launch Week (Week 3)

| Day | Channel | Content |
|-----|---------|---------|
| Mon | Twitter | "Building a habit tracker. One rule: no streaks. 🧵" |
| Tue | Twitter | Dev diary: 1-tap check-in prototype |
| Wed | Twitter | The problem with habit apps (thread) |
| Thu | Twitter | Privacy-first design decisions |
| **Fri** | **Product Hunt** | **Launch! "The habit tracker that doesn't make you feel bad"** |
| **Fri** | **HN** | **Show HN: Habit Hive — open source, privacy-first habit tracker** |
| Sat | Twitter | Launch results + thank you |
| Sun | Weekly digest | First automated weekly digest goes out |

## Post-Launch (Week 4–5)

| Day | Channel | Content |
|-----|---------|---------|
| Week 4 | dev.to | "I built a habit tracker without streaks. Here's why." |
| Week 4 | Reddit | r/SideProject + r/privacy posts |
| Week 5 | Twitter | "One month of Habit Hive — retention numbers (honest)" |
| Week 5 | Newsletter | First monthly update to email list |

## Voice & Tone

- Warm, human, honest
- "We're building this for ourselves, and sharing it with you"
- No startup jargon (no "disrupt", "leverage", "synergy")
- Acknowledge imperfection — this is v0, not the final product
`,
  },
};

// ─── Helpers ──────────────────────────────────────────────────────────────────

function sleep(ms) {
  return new Promise((r) => setTimeout(r, ms));
}

const SPINNER = ["⠋", "⠙", "⠹", "⠸", "⠼", "⠴", "⠦", "⠧", "⠇", "⠏"];
const STAGES = [
  { key: "01-discovery", agent: "problem-discoverer", gateName: "Problem Statements" },
  { key: "02-validation", agent: "opportunity-validator", gateName: "Opportunity Validation" },
  { key: "03-current-state", agent: "current-state-expert", gateName: "Current State Assessment" },
  { key: "04-solutions", agent: "solution-generator", gateName: "Solution Selection" },
  { key: "05-assessment", agent: "solution-assessor", gateName: "Solution Assessment" },
  { key: "06-design", agent: "ux-designer", gateName: "UX Design" },
  { key: "07-design-review", agent: "ux-design-lead", gateName: "Design Review" },
  { key: "08-project-plan", agent: "project-manager", gateName: "Project Plan" },
  { key: "09-gtm", agent: "gtm-designer", gateName: "GTM Plan" },
  { key: "10-feedback", agent: "feedback-manager", gateName: "Feedback Setup" },
  { key: "11-communications", agent: "communications-specialist", gateName: "Communications" },
];

const GATES = STAGES.map((s, i) => ({
  num: i + 1,
  name: s.gateName,
  status: i < 8 ? "approved" : i === 8 ? "needs-input" : "pending",
}));

function formatDuration(ms) {
  const secs = Math.floor(ms / 1000);
  if (secs < 60) return `${secs}s`;
  return `${Math.floor(secs / 60)}m ${secs % 60}s`;
}

async function showSpinner(label, durationMs = 800) {
  const start = Date.now();
  let i = 0;
  return new Promise((resolve) => {
    const interval = setInterval(() => {
      const elapsed = Date.now() - start;
      const pct = Math.min(100, Math.round((elapsed / durationMs) * 100));
      process.stdout.write(
        `\r  ${SPINNER[i % SPINNER.length]} ${label} ${pct}%`
      );
      i++;
    }, 60);
    setTimeout(() => {
      clearInterval(interval);
      process.stdout.write(`\r  ✅ ${label} ${formatDuration(durationMs)}\n`);
      resolve();
    }, durationMs);
  });
}

function writeFiles(baseDir, tree, parentPath = "") {
  for (const [key, value] of Object.entries(tree)) {
    const fullPath = path.join(baseDir, parentPath, key);
    if (typeof value === "string") {
      fs.mkdirSync(path.dirname(fullPath), { recursive: true });
      fs.writeFileSync(fullPath, value.trimStart() + "\n");
    } else {
      fs.mkdirSync(fullPath, { recursive: true });
      writeFiles(baseDir, value, path.join(parentPath, key));
    }
  }
}

function writeGates(baseDir) {
  const gatesMd = `# Gates — Decision Log

> This file is the control plane. Every agent checks it before proceeding.
> The human marks gates as: \`approved\`, \`blocked\`, \`needs-input\`, or
> \`revision-needed\`.

${GATES.map(
  (g, i) => `## Gate ${g.num}: ${g.name}
- **status**: ${g.status}
- **agent**: ${STAGES[i].agent}
- **artifacts**: ${STAGES[i].key}/
- **summary**: ${i < 8 ? "Pipeline stage completed and approved." : i === 8 ? "Launch plan drafted. Needs review before proceeding." : "Awaiting previous gate approval."}
`
).join("\n")}
`;

  fs.writeFileSync(path.join(baseDir, "gates.md"), gatesMd.trimStart() + "\n");
}

function writePipeline(baseDir) {
  const stageRows = STAGES.map((s, i) => {
    const status = i < 9 ? "✅ Complete" : "⏳ Pending";
    const gate = i < 8 ? "✅" : i === 8 ? "⏳ Needs review" : "⏳";
    return `| ${s.key} | ${s.agent} | ${status} | Gate ${i + 1} ${gate} |`;
  }).join("\n");

  const pipelineMd = `# Pipeline State

> Auto-updated by agents. Human-readable status of the current project.

## Project
- **Name**: Habit Hive
- **Idea**: A minimal, privacy-first habit tracker
- **Mode**: mvp
- **Created**: ${new Date().toISOString().split("T")[0]}

## Status

| Stage | Agent | Status | Gates |
|-------|-------|--------|-------|
${stageRows}
## Next Action

Gate 9 (GTM Plan) needs your review. Run:
\`\`\`
pm-pipeline approve 9
pm-pipeline next
\`\`\`
`;

  fs.writeFileSync(
    path.join(baseDir, "pipeline.md"),
    pipelineMd.trimStart() + "\n"
  );
}

// ─── Main ─────────────────────────────────────────────────────────────────────

async function main() {
  const outDir = path.resolve(process.argv[2] || "__demo__");

  if (fs.existsSync(outDir)) {
    console.error(`❌ Directory "${outDir}" already exists. Remove it first or use a different path.`);
    process.exit(1);
  }

  console.log("\n  🐝 Habit Hive — PM Agent Pipeline Demo\n");

  // Phase 0: Write idea
  fs.mkdirSync(outDir, { recursive: true });
  fs.writeFileSync(path.join(outDir, "Idea.md"), DEMO_IDEA.trimStart() + "\n");
  console.log("  📄 Idea written: Build a habit tracking app\n");

  // Phases 1–11: Write each agent's output
  const startTime = Date.now();

  for (const stage of STAGES) {
    const label = `Stage ${stage.key}: ${stage.agent}`;

    await showSpinner(label, 350 + Math.random() * 400);

    const content = DEMO_CONTENT[stage.key];
    if (content) {
      writeFiles(outDir, { [stage.key]: content });
    }
  }

  // Write gates.md and pipeline.md
  await showSpinner("Writing gates.md & pipeline.md", 300);
  writeGates(outDir);
  writePipeline(outDir);

  // Summary
  const elapsed = Date.now() - startTime;
  const totalFiles = countFiles(outDir);

  console.log(`\n  ─────────────────────────────────────────`);
  console.log(`  ✅ Demo complete!`);
  console.log(`  📁 Output: ${outDir}`);
  console.log(`  📄 Files generated: ${totalFiles}`);
  console.log(`  ⏱️  Time: ${formatDuration(elapsed)}`);
  console.log(`\n  🚀 Try it yourself:`);
  console.log(`     node scripts/demo.js my-project`);
  console.log(`     cd my-project`);
  console.log(`     cat gates.md    # see pipeline state`);
  console.log(`     cat 09-gtm/launch-plan.md`);
  console.log(`\n  📊 Pipeline is paused at Gate 9 (GTM Plan) — needs your review.`);
  console.log(`     Mark it approved and the next agent can proceed.\n`);
}

function countFiles(dir) {
  let count = 0;
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    if (entry.isFile()) count++;
    else if (entry.isDirectory()) count += countFiles(path.join(dir, entry.name));
  }
  return count;
}

main().catch((err) => {
  console.error("\n❌ Demo failed:", err.message);
  process.exit(1);
});
